// auth.js
export const LOGOUT = 'LOGOUT'
export const SAVE_TOKEN = 'SAVE_TOKEN'
export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export const UPDATE_USER = 'UPDATE_USER'

export const FETCH_PODCASTS = 'FETCH_PODCASTS'
export const FETCH_PODCASTS_SUCCESS = 'FETCH_PODCASTS_SUCCESS'
export const FETCH_PODCASTS_FAILURE = 'FETCH_PODCASTS_FAILURE'

// lang.js
export const SET_LOCALE = 'SET_LOCALE'
